### ISSUE TITLE
Speed uses wrong unit

### ISSUE THREAD

**Issue by MeijiRestored** [Freika/dawarich#700]
I noticed that the speeds indicated on map are way off from reality :

![Image](https://github.com/user-attachments/assets/82681d4f-b072-43f6-88a1-f1c408e9b72f)
Real speed : 100km/h

![Image](https://github.com/user-attachments/assets/bbd74f79-4da7-413f-ac50-e969bcd0be83)
Real speed : ~50km/h

I reviewed this further and found out that the numbers indicated here are the speeds in m/s :
360 m/s = 100 km/h.

So it seems the map shows speeds in m/s but labels them as km/h.

**Comment by ramess18** [comment]
I also experiencing this weird speed. Map is not showing speed in m/s ..."your" 169 m/s would be 608 km/h ;) By my observation for example your 169 km/h is in real 47 km/h - 169/3,6=47

**Comment by Freika** [comment]
@MeijiRestored @ramess18 what do you use to track your data? Is it Owntracks or other software?

**Comment by MeijiRestored** [comment]
I use owntracks. Also sorry for the poor explanation, indeed what is shown is not m/s but rather km/h multiplied by 3.6

**Comment by ramess18** [comment]
@Freika I use GPSLogger.

**Comment by tjorim** [comment]
For the home assistant integration we actually needed to feed the data points as km/h (the HA companion app provides them as m/s) to Dawarich or I would see too low speeds.

**Comment by marsmathis** [comment]
I have the same problem (I use %SPD_KPH in GPSLogger). I figure I should have been using %SPD (which is in m/s) but by now I have a few months of wrong velocity data in my dawarich account.

**Comment by ramess18** [comment]
Thanks @marsmathis - I tested today to change %SPD_KPH to %SPD in GPSLogger and it seems to be the solution.

Please @Freika make the Docs  correction - https://dawarich.app/docs/tutorials/track-your-location#gps-logger

**Comment by MeijiRestored** [comment]
As for Owntracks it seems I cannot change the unit. Points recorded with Owntracks would need to have their speed corrected by Dawarich

**Comment by ramess18** [comment]
I was talking about GPSLogger and the specific Doc paragraph describing setting in GPSLogger . I don't use Owntracks ;).

**Comment by Freika** [comment]
Let's sum this up before I proceed with the fix.

Each app transfers speed data in either km/h or m/s.

- Overland — m/s
- Dawarich — m/s
- GPSLogger — km/h OR m/s depending on the settings
- OwnTracks — km/h
- HomeAssistant — ???

Am I missing something here?

**Comment by tjorim** [comment]
Home Assistant natively uses m/s.

**Comment by Freika** [comment]
Good, then I'll soon provide a script to convert existing data to m/s for those who were tracking with owntracks or gpslogger in km/h

**Comment by marsmathis** [comment]
@Freika that would be good. However, my imported data from Google Timeline has the correct velocities. How do we ensure in the script that only the data that was uploaded from GPSLogger gets converted, and within that only the wrong data before rectifying the variable in the upload? I have thus far refrained to change from %SPD_KPH to %SPD because I am unsure whether this would mess with the conversion later.

**Comment by Freika** [comment]
> [@Freika](https://github.com/Freika) that would be good. However, my imported data from Google Timeline has the correct velocities. How do we ensure in the script that only the data that was uploaded from GPSLogger gets converted, and within that only the wrong data before rectifying the variable in the upload? I have thus far refrained to change from %SPD_KPH to %SPD because I am unsure whether this would mess with the conversion later.

Yes, there might be a problem.

Basically, we're safe with all the points that were _imported_, because we can distinguish them with existing `import_id` attr  and don't touch them at all. However, if a user was tracking, say, with both GPSLogger (m/s) and Owntracks (km/h), it's a problem, because we can't really distinguish between them. Or, I'd rather say, I may suggest which point was tracked by what software based on their raw data, but it's not a 100% guarantee.

But we'll see when I'll start working on it, maybe it's not as bad.

**Comment by timwds** [comment]
For your sanity, here is the raw SQL row vs GUI. Data collected with Owntracks on android. DB has 51 which represents kmh. It looks like Dawarich has assumed m/s and converted to kmh (51 Meters per Second = 183.6 Kilometers per Hour). I'm not seeing an option in owntracks to change it so must be based on device region settings??

Timestamp: 25/01/2025, 18:32:41
Latitude: -31.763018
Longitude: 150.833527
Altitude: 510m
Speed: 184km/h
Battery: 53%
Id: 220523
[[Delete]](http://192.168.4.54:3000/map#)


"id"	"battery_status"	"ping"	"battery"	"tracker_id"	"topic"	"altitude"	"longitude"	"velocity"	"trigger"	"bssid"	"ssid"	"connection"	"vertical_accuracy"	"accuracy"	"timestamp"	"latitude"	"mode"	"inrids"	"in_regions"	"raw_data"	"import_id"	"city"	"country"	"created_at"	"updated_at"	"user_id"	"geodata"	"visit_id"	"reverse_geocoded_at"	"course"	"course_accuracy"	"external_track_id"
220523	1		53	"do"	"owntracks/user/komodo"	510	150.833527	"51"	0			0	18	29	1737790361	-31.763018				"{""m"": 2, ""bs"": 1, ""_id"": ""e887591e"", ""acc"": 29, ""alt"": 510, ""cog"": 305, ""lat"": -31.7630184, ""lon"": 150.8335265, ""tid"": ""do"", ""tst"": 1737790361, ""vac"": 18, ""vel"": 51, ""batt"": 53, ""conn"": ""m"", ""_type"": ""location"", ""point"": {""topic"": ""owntracks/user/komodo"", ""created_at"": 1737790362}, ""topic"": ""owntracks/user/komodo"", ""action"": ""create"", ""api_key"": """", ""controller"": ""api/v1/owntracks/points"", ""created_at"": 1737790362}"				"2025-01-25 07:32:42.386345"	"2025-01-25 07:32:42.386345"	1	"{}"

**Comment by MeijiRestored** [comment]
> However, if a user was tracking, say, with both GPSLogger (m/s) and Owntracks (km/h), it's a problem, because we can't really distinguish between them.

Checking point data, it seems the tracking method is recorded in the "topic" value, at least for owntracks, see here with this point :

![Image](https://github.com/user-attachments/assets/43c24ce9-4b81-4fd1-b723-09e86fefcfed)

**Comment by Erdenian** [comment]
I noticed that speed is wrong only on 'Map' page

![Image](https://github.com/user-attachments/assets/cb95ce7a-4d8d-424d-89cc-ff4e91f31232)

the same point on 'Points' page has correct speed

![Image](https://github.com/user-attachments/assets/2b09ad9c-dffd-4f30-b40a-a4406108b278)

**Comment by Freika** [comment]
I'll fix it in the next release

**Comment by Freika** [comment]
I think this was resolved

**Comment by zivillian** [comment]
I noticed the same issue today on 0.26.7. I'm using Owntracks and the speed is wrong on points page

![Image](https://github.com/user-attachments/assets/eec26567-c3f3-4871-be7d-ea5637e91687)

correct in the **points** tooltip in the map

![Image](https://github.com/user-attachments/assets/c5360ad7-a78f-4231-af2e-b5450d61589b)

and also wrong in the route tooltip in the map

![Image](https://github.com/user-attachments/assets/8d46423e-f801-46f2-a410-6429781d2d0d)

**Comment by Erdenian** [comment]
> I noticed the same issue today on 0.26.7. I'm using Owntracks and the speed is wrong on points page

I have the opposite, correct speed on "Map" page

![Image](https://github.com/user-attachments/assets/94f97d46-4f80-496b-a287-ecb0df3ed53c)

But wrong speed on "Points" page

![Image](https://github.com/user-attachments/assets/bad23b4e-aaf4-4c56-bdcd-6c59610e0f8d)

Maybe you didn't run
```
points.update_all("velocity = CAST(ROUND(CAST((CAST(velocity AS FLOAT) * 1000 / 3600) AS NUMERIC), 1) AS TEXT)")
```
after update to 0.24.0 as suggested in the [release notes](https://github.com/Freika/dawarich/releases/tag/0.24.0).

But after all it seems that this issue is not resolved yet in 0.26.7.

@Freika

**Comment by Freika** [comment]
Please update to the latest version and see if issue persists

**Comment by Erdenian** [comment]
Issue persists on version 0.27.3

Map
![Image](https://github.com/user-attachments/assets/f87db9c9-ae8e-4b51-b532-af87c096ad92)

Points
![Image](https://github.com/user-attachments/assets/44437d7f-9b96-4aec-ac16-227d39f5bfd6)

I'll try version 0.27.4-rc.1

**Comment by Erdenian** [comment]
Same on version 0.27.4-rc.1

Map
![Image](https://github.com/user-attachments/assets/ab300717-f518-4d97-a6bf-a10957af8888)

Points
![Image](https://github.com/user-attachments/assets/59cdb9c3-250b-4c2d-b37d-b0a764484e3b)

**Comment by zivillian** [comment]
I can confirm that the issue persists with 0.28.1

**Comment by narucx** [comment]
Im on 0.28.1 and for me it shows the kms value in points and map lol
If i multiply the values with 3.6 I get to the correct kmh value

![Image](https://github.com/user-attachments/assets/3ab78ccd-803b-4074-abe2-a292287e95e1)

![Image](https://github.com/user-attachments/assets/cbd9bc3a-66ae-4288-b4c1-a90e8504588f)

![Image](https://github.com/user-attachments/assets/c40a82ee-bfb8-49b0-ba20-0bf0bf059a17)

**Comment by narucx** [comment]
I have an even better example
I dont think that my plane flew with 170-220 km/h

Im using Owntracks as tracker

![Image](https://github.com/user-attachments/assets/9f562c00-97d7-4161-8ce0-5dc3150badd9)

![Image](https://github.com/user-attachments/assets/222172d5-44ad-4d8d-bffe-b7dd5e0483f3)
